CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migrationid character varying(150) NOT NULL,
    productversion character varying(32) NOT NULL,
    CONSTRAINT pk___efmigrationshistory PRIMARY KEY (migrationid)
);

START TRANSACTION;
CREATE TABLE associates (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    identification character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    CONSTRAINT pk_associates PRIMARY KEY (id)
);

CREATE TABLE credits (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    creditnumber character varying(50) NOT NULL,
    associateid integer NOT NULL,
    credittype character varying(50) NOT NULL,
    requestedvalue numeric(18,2) NOT NULL,
    interestrate numeric(18,2) NOT NULL,
    numberofinstallments integer NOT NULL,
    paymentmethod character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    requestdate timestamp with time zone NOT NULL,
    updatedate timestamp with time zone NOT NULL,
    CONSTRAINT pk_credits PRIMARY KEY (id),
    CONSTRAINT fk_credits_associates_associateid FOREIGN KEY (associateid) REFERENCES associates (id) ON DELETE RESTRICT
);

CREATE TABLE credithistories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    creditid integer NOT NULL,
    previousstatus character varying(50) NOT NULL,
    newstatus character varying(50) NOT NULL,
    changedate timestamp with time zone NOT NULL,
    observation character varying(500) NOT NULL,
    "user" character varying(100) NOT NULL,
    CONSTRAINT pk_credithistories PRIMARY KEY (id),
    CONSTRAINT fk_credithistories_credits_creditid FOREIGN KEY (creditid) REFERENCES credits (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_associates_identification ON associates (identification);

CREATE INDEX ix_credits_associateid ON credits (associateid);

CREATE UNIQUE INDEX ix_credits_creditnumber ON credits (creditnumber);

CREATE INDEX ix_credithistories_creditid ON credithistories (creditid);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20261001020727_InitialCreate', '9.0.20');

COMMIT;
