version: '3.8'

services:
  db:
    image: postgres:16
    container_name: opa_postgres_db
    environment:
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: TuPassword
      POSTGRES_DB: OPA
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admindb -d OPA"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opa_credits_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=OPA;Username=admindb;Password=TuPassword
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

volumes:
  pgdata:
