version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opa_credits_api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=72.61.70.56;Port=5432;Database=OPA;Username=admindb;Password=AceroBronce2560*
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - default
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opa-api.rule=Host(`api-credits.cephasco.com`)"
      - "traefik.http.routers.opa-api.entrypoints=websecure"
      - "traefik.http.routers.opa-api.tls.certresolver=mytlschallenge"
      - "traefik.http.services.opa-api.loadbalancer.server.port=8080"
      - "traefik.docker.network=root_default"

networks:
  default:
  root_default:
    external: true
