// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Opa.Credits.Infrastructure.Persistence;

#nullable disable

namespace Opa.Credits.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001020727_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Asociado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_asociados");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("ix_asociados_identificacion");

                    b.ToTable("asociados", (string)null);
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Credito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AsociadoId")
                        .HasColumnType("integer")
                        .HasColumnName("asociadoid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaactualizacion");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechasolicitud");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("formapago");

                    b.Property<string>("NumeroCredito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numerocredito");

                    b.Property<int>("NumeroCuotas")
                        .HasColumnType("integer")
                        .HasColumnName("numerocuotas");

                    b.Property<decimal>("TasaInteres")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tasainteres");

                    b.Property<string>("TipoCredito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipocredito");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorsolicitado");

                    b.HasKey("Id")
                        .HasName("pk_creditos");

                    b.HasIndex("AsociadoId")
                        .HasDatabaseName("ix_creditos_asociadoid");

                    b.HasIndex("NumeroCredito")
                        .IsUnique()
                        .HasDatabaseName("ix_creditos_numerocredito");

                    b.ToTable("creditos", (string)null);
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.HistorialCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditoId")
                        .HasColumnType("integer")
                        .HasColumnName("creditoid");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estadoanterior");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estadonuevo");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacambio");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacion");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_historialcreditos");

                    b.HasIndex("CreditoId")
                        .HasDatabaseName("ix_historialcreditos_creditoid");

                    b.ToTable("historialcreditos", (string)null);
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Credito", b =>
                {
                    b.HasOne("Opa.Credits.Domain.Entities.Asociado", "Asociado")
                        .WithMany("Creditos")
                        .HasForeignKey("AsociadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_creditos_asociados_asociadoid");

                    b.Navigation("Asociado");
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.HistorialCredito", b =>
                {
                    b.HasOne("Opa.Credits.Domain.Entities.Credito", "Credito")
                        .WithMany("Historiales")
                        .HasForeignKey("CreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historialcreditos_creditos_creditoid");

                    b.Navigation("Credito");
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Asociado", b =>
                {
                    b.Navigation("Creditos");
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Credito", b =>
                {
                    b.Navigation("Historiales");
                });
#pragma warning restore 612, 618
        }
    }
}
