// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Opa.Credits.Infrastructure.Persistence;

#nullable disable

namespace Opa.Credits.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001102624_EnglishTranslation")]
    partial class EnglishTranslation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Associate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_asociados");

                    b.HasIndex("Identification")
                        .IsUnique()
                        .HasDatabaseName("ix_asociados_identification");

                    b.ToTable("asociados", (string)null);
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociateId")
                        .HasColumnType("integer")
                        .HasColumnName("associateid");

                    b.Property<string>("CreditNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("creditnumber");

                    b.Property<string>("CreditType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("credittype");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("interestrate");

                    b.Property<int>("NumberOfInstallments")
                        .HasColumnType("integer")
                        .HasColumnName("numberofinstallments");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymentmethod");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestdate");

                    b.Property<decimal>("RequestedValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("requestedvalue");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedate");

                    b.HasKey("Id")
                        .HasName("pk_creditos");

                    b.HasIndex("AssociateId")
                        .HasDatabaseName("ix_creditos_associateid");

                    b.HasIndex("CreditNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_creditos_creditnumber");

                    b.ToTable("creditos", (string)null);
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.CreditHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changedate");

                    b.Property<int>("CreditId")
                        .HasColumnType("integer")
                        .HasColumnName("creditid");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("newstatus");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observation");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("previousstatus");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_historialcreditos");

                    b.HasIndex("CreditId")
                        .HasDatabaseName("ix_historialcreditos_creditid");

                    b.ToTable("historialcreditos", (string)null);
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Credit", b =>
                {
                    b.HasOne("Opa.Credits.Domain.Entities.Associate", "Associate")
                        .WithMany("Credits")
                        .HasForeignKey("AssociateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_creditos_asociados_associateid");

                    b.Navigation("Associate");
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.CreditHistory", b =>
                {
                    b.HasOne("Opa.Credits.Domain.Entities.Credit", "Credit")
                        .WithMany("Histories")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historialcreditos_creditos_creditid");

                    b.Navigation("Credit");
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Associate", b =>
                {
                    b.Navigation("Credits");
                });

            modelBuilder.Entity("Opa.Credits.Domain.Entities.Credit", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
